### ISSUE TITLE
Texture Crash

### ISSUE THREAD

**Issue by Warrriorrr** [MJRLegends/Space-Astronomy-Feedback-#895] opened 2017-06-28 04:33 UTC
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes
### Steps to Reproduce Issue
1. Log into twitch client.
2. Go to Minecraft and download Space Astronomy
3. Attempt to load into the game's main menu.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
Very unfortunately, the "View Crash Report" button does not even do anything. They give me such a SMALL amount of information that I don't even think a pastebin will matter:

The game crashed whilst registering texture
The game crashed whilst registering texture
Error: java.lang.RuntimeException: Can't fit all textures, use lower resolution texture packs or remove mods.

**Version of Mod Pack using:** [VERSION]
1.6.7

### Additional Information
[Any other information that may be able to help me with the problem]
IF. This is a ram issue, how do I fix it? I've tried through the mc client, AND the twitch client, but neither did anything when I attempted to change them.

**Comment by MJRLegends** [comment] 2017-06-28 12:23
Are you using a texture pack?
and how much ram do you assign to the pack?

**Comment by Warrriorrr** [comment] 2017-06-28 14:38
I was NOT using a texture pack when I first got this issue, then I fixed it SOMEHOW (I can't reproduce a fix even though im doing the same things) I DO have a texture pack now but attempted to remove it as a fix, and it did not work.

I only had the default set for awhile, then I assigned 12g, no change.

**Comment by MJRLegends** [comment] 2017-06-28 14:48
Try removing the texture pack

**Comment by Warrriorrr** [comment] 2017-06-28 16:31
Deleted the entirety of the pack and reinstalled, no texture packs, issue persists, any idea?

**Comment by MJRLegends** [comment] 2017-06-28 16:32
Ok does any other pack work?

**Comment by Warrriorrr** [comment] 2017-06-28 17:04
Yes. I fixed it by deleting every pack I had installed, and reinstalling again. It worked, but i'm unsure why I have to reinstall every time I want to take a break from the game... Unfortunate but I can deal with it.

**Comment by Warrriorrr** [comment] 2017-06-28 17:13
Okay nevermind, I think I narrowed it down.

I thought it worked because I was on 1.6.6, but I need 1.6.7.

After updating to 1.6.7, I get the texture issue.

**Closed** 2017-06-28 20:48 UTC
Labels: being looked at, cant reproduce, client/user issue only, waiting on reply

**Comment by MJRLegends** [comment] 2018-11-11 17:41
Issue is caused by GPU being to old to store all textures
