### ISSUE TITLE
Wood Planks Dupe Bug.

### ISSUE THREAD

**Issue by mario308** [MJRLegends/Space-Astronomy-Feedback-#528] opened 2016-09-16 01:01 UTC
### ---Issue Report---
**Have you checked the Known Issues page (if applicable):** [Yes]

**Have you checked Closed Issues (if applicable):** [Yes]
### Description of Issue
It takes 7 planks to make 4 oak trims (any wood trims) from Storage Drawers but putting 1 trim in Thermal Expansion's saw mill gives you 5 planks and a saw dust. So for 7 planks you get 20 in return.
### Steps to Reproduce Issue
1. Craft 4 trims from Storage Drawers. (It takes 5 planks and 4 sticks which is essentially 7 planks).
2. Put each trim in Thermal Expansion's saw mill and you will get 20 planks and 5 saw dust.

**Version of Mod Pack using:** [1.5.3]

**Comment by MJRLegends** [comment] 2016-10-04 15:14
@mario308 Cant reproduce this 
Test 1 - Single Player
![](https://i.gyazo.com/e5c491a06fa357e2698c1c6d168dff2e.gif)

Test 2 - Multiplayer
![](https://i.gyazo.com/cea441120230c878ed503e2b15522bd0.gif)

**Comment by AWaRFISH** [comment] 2016-10-05 10:55
The OP said to craft 4 trims, then put **all 4** in the sawmill with a return of 20 planks for a cost of 7 planks to make 4 trims

**Comment by MJRLegends** [comment] 2016-10-05 10:59
Yeah but they only take 5 planks to make and you dont get sticks???

**Comment by MJRLegends** [comment] 2016-10-05 11:02
Yeah but i dont see how its a dupe bug??

**Comment by AWaRFISH** [comment] 2016-10-05 11:03
Not actually a dupe bug per say, but you get almost get 3x planks back after using 7 to make 4 trims

**Comment by MJRLegends** [comment] 2016-10-05 11:05
How are you getting 3x when it gives you 5 back and a saw dust per plank??

**Comment by AWaRFISH** [comment] 2016-10-05 11:06
you do get 5 PER trim, so multiply that by 4 (cost of 7 planks) and you get 20 planks and 4 sawdust

**Comment by MJRLegends** [comment] 2016-10-05 11:07
Sorry but you use 7 planks per trim and you get 5 planks and a saw dust back so how is that a dupe bug???

**Comment by AWaRFISH** [comment] 2016-10-05 11:09
it costs 7 planks to make 4 trims... You get back 5 planks each trim that is in the sawmill, so 5 planks x 4 trims = 20 planks in return

**Comment by MJRLegends** [comment] 2016-10-05 11:11
Will be fixed for v1.5.4

**Comment by AWaRFISH** [comment] 2016-10-05 11:12
Nice :)

**Comment by MJRLegends** [comment] 2016-10-10 22:43
Will be fixed in v1.5.4 and has been added to the known issues here http://pastebin.com/R73aBeqA

**Closed by MJRLegends** 2016-10-10 22:43 UTC
Labels: compatibility issue, dupe bug, fixed in next update, mod bug, MUST SEE
