### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by ognjen92** [MJRLegends/Space-Astronomy-Feedback-#145] opened 2015-12-11 18:08 UTC
game crashes every time i whant to see recipe in nei with v 1.3.2, but it was fine in v 1.3.1

**Comment by ognjen92** [comment] 2015-12-11 18:08
i am using ftb

**Comment by MJRLegends** [comment] 2015-12-11 18:14
I'm using the same mods as v1.3.0 had and no one reported that crash during v1.3.0 but v1.3.1 had the crash.

**Comment by MJRLegends** [comment] 2015-12-11 18:14
Try reinstalling the mod pack

**Comment by ognjen92** [comment] 2015-12-12 01:38
i reinstaled it and its the same :/

**Comment by ognjen92** [comment] 2015-12-12 01:53
i now made new world and it works, but with my save from v1.3.1 it crases :/

**Comment by MJRLegends** [comment] 2015-12-12 01:55
oh i dont really know what to suggest.

**Comment by WalaoEgg0424** [comment] 2015-12-12 02:14
@ognjen92 crashlog?

**Comment by ognjen92** [comment] 2015-12-12 02:21
i hope that this is crash log, http://www.mediafire.com/download/oyw0vzgl6jwnthz/hs_err_pid4860.log

**Comment by MJRLegends** [comment] 2015-12-12 02:23
@ognjen92 thats not the correct crash log thats a error with Java Runtime Environment

**Comment by ognjen92** [comment] 2015-12-12 02:23
where do i find crash log?

**Comment by MJRLegends** [comment] 2015-12-12 02:24
Folder: ftblauncher\SpaceAstronomy\minecraft\crash-reports

**Comment by ognjen92** [comment] 2015-12-12 02:26
here it is : http://www.mediafire.com/download/k4me0dvvnak4244/crash-2015-12-12_02.36.42-client%282%29.txt

**Comment by MJRLegends** [comment] 2015-12-12 02:29
See https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/450

**Comment by MJRLegends** [comment] 2015-12-12 02:31
This is a mod bug but it was crash more in v1.3.1 due to another mod

**Comment by ognjen92** [comment] 2015-12-12 02:32
yea but i dont know which mod is doing it :/

**Comment by WalaoEgg0424** [comment] 2015-12-12 02:33
Are you sure that your using v1.3.2?

**Comment by ognjen92** [comment] 2015-12-12 02:34
yes i am

**Comment by MJRLegends** [comment] 2015-12-12 02:34
Is a mix of different bugs but Reika has said its a problem in RotaryCraft. But im not sure if it fully is

**Comment by ognjen92** [comment] 2015-12-12 02:35
kk i will try to remove rotarycraft and see if will be fixed

**Comment by MJRLegends** [comment] 2015-12-12 02:38
Ok, I'm in the middle of tracking it down but its hard because it doesn't seem to be all one mod that is triggering it but once RotaryCraft has update it should be fixed all together

**Comment by ognjen92** [comment] 2015-12-12 02:59
it wont even start when i remove rotarycraft, well then i will wait until they update rotary craft :(

**Comment by WalaoEgg0424** [comment] 2015-12-12 03:21
@ognjen92 The only solution now is disable NEI ingame by pressing O , then if u need recipe , google it.
 
I do this too to prevent play until half accidentely click the NEI recipe.

**Comment by DaneD96** [comment] 2015-12-12 04:00
http://www.reddit.com/r/feedthebeast/comments/3w5jzw/space_astronomy_crash_nei/

I posted this a few days ago, Reika said it was fixed...

**Comment by WalaoEgg0424** [comment] 2015-12-12 04:02
@DaneD96 Reika said that it was fixed in v10b , but Reika havent publish the RotaryCraft v10b. MJRLegends is waiting for RotaryCraft update so that other mods can update to latest version.

**Comment by DaneD96** [comment] 2015-12-12 04:19
I see, thanks for clarifying

**Comment by WalaoEgg0424** [comment] 2015-12-12 04:20
@DaneD96 Your Welcome :)

**Comment by ognjen92** [comment] 2015-12-12 10:47
Tnx, for the help , i will disable nei for now :)

**Comment by WalaoEgg0424** [comment] 2015-12-12 11:05
@ognjen92 The NEI doesnt crash for me eventhough i am playing my v1.3.1 world & world backup. Try make a backup of your old world , delete the whole modpack , install the modpack again.

**Comment by ognjen92** [comment] 2015-12-12 12:22
i did that already, and found out that its only crashing with my worlds from 1.3.1, and when i make new world in 1.3.2 it not crasing

**Comment by ognjen92** [comment] 2015-12-12 12:23
and i didnt have any crashing in v1.3.1 only now in 1.3.2

**Comment by WalaoEgg0424** [comment] 2015-12-12 12:23
@ognjen92 Thats weird , for me , my 1.3.1 world dont crash.

**Comment by MJRLegends** [comment] 2015-12-13 00:31
Yeah i cant reproduce this crash, can you send me a copy of the world.

**Comment by ognjen92** [comment] 2015-12-13 14:13
I will upload it tonight, am not home right now.

**Comment by ognjen92** [comment] 2015-12-13 16:20
here it is : http://www.mediafire.com/download/u58vm7vbl3xv8lk/space.rar

**Comment by MJRLegends** [comment] 2015-12-17 02:13
Sorry for the late reply but I cant reproduce this problem.

**Closed** 2015-12-19 01:11 UTC
Labels: being looked at, cant reproduce, mod bug, wont/cant fix
