### ISSUE TITLE
Black Screen and OpenGL Error 1280 (Invalid Enum)

### ISSUE THREAD

**Issue by testinstien** [MJRLegends/Space-Astronomy-Feedback-#470] opened 2016-08-10 18:28 UTC
Ever since my screen went black after taking a syringe with night vision, fly, teleport, teleport items and resistance this happens. It started once I put night vision on the syringe. I can't walk into anything that's not a full block like wires,torches,etc or my screen will go black. My chat gets notifications with "OpenGL Error 1280 (Invalid Enum)" and I have tried reinstalling drivers, java, minecraft, Astronomy, and curse yet nothing has happened. I've installed Optifine to try to help but that did nothing also. "OpenGL error 1280 (Invalid Enum) in yellow and white in chat. I've asked around and apparently it doesn't happen to other people
 The chests were also something that happened when I got night vision

Going into a block that's not full torch, wire, slab, etc
![2016-08-10_12 04 21](https://cloud.githubusercontent.com/assets/11904212/17559118/5b0a0e5c-5ef3-11e6-8f2e-ba37425e0258.png)

Not in one
![2016-08-10_12 04 18](https://cloud.githubusercontent.com/assets/11904212/17559144/7274730c-5ef3-11e6-9eb5-86cf8d1b1ecf.png)

Crystal Chests look like diamond chests
![2016-08-10_12 20 52](https://cloud.githubusercontent.com/assets/11904212/17565440/e201ba44-5f0d-11e6-8297-88c24b8fa52a.png)

**Comment by MJRLegends** [comment] 2016-08-10 20:00
Are you using OptiFine

**Comment by MJRLegends** [comment] 2016-08-10 20:01
If not try remove fastcraft

**Comment by MJRLegends** [comment] 2016-08-10 20:02
Also 'galacticraft' planets and 'more planets' planets dont work with night vision so it will be black

**Comment by testinstien** [comment] 2016-08-10 23:12
It did it even without OptiFine and my friend can use night vision on the different planets fine. I've asked 3 people and they said it worked fine.

**Comment by testinstien** [comment] 2016-08-10 23:13
2 of them use Curse launcher

**Comment by MJRLegends** [comment] 2016-08-10 23:16
Its a known bug with galacticraft that night vision doesnt work on their planets..... Example one https://forum.micdoodle8.com/index.php?threads/moon-is-black.681/ example two https://github.com/micdoodle8/Galacticraft/issues/752

**Comment by MJRLegends** [comment] 2016-08-10 23:17
the Galacticraft dont know how to fix it, so i say this issue is resolved in the fact we have found the cause and its already known by me and the mod devs and loads of uses of the mod Galacticraft

**Comment by testinstien** [comment] 2016-08-10 23:18
So no way to fix it right now?

**Comment by MJRLegends** [comment] 2016-08-10 23:19
Yeah you just need to remove your night vision and not use it on planets

**Comment by MJRLegends** [comment] 2016-08-10 23:20
Sorry i wish i could fix this for you but its been like it for years :/

**Comment by testinstien** [comment] 2016-08-10 23:20
Any way to disable the night vision effect cause I have it perm.

**Closed by MJRLegends** 2016-08-10 23:19 UTC
Labels: already known issue, mod bug, reported to developer, unable to fix, wont/cant fix

**Comment by MJRLegends** [comment] 2016-08-10 23:22
You need to craft a Anti gene see https://forum.feed-the-beast.com/threads/complete-advanced-genetics-guide-becoming-supernatural.45846/ for help on that
